import 'bootstrap/dist/css/bootstrap.min.css';
import './globals.css'; // Keep your custom styles

export const metadata = {
  title: "My Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
